!!python/object/apply:collections.OrderedDict
- - - batch_size
    - 64
  - - clip_range
    - 0.2
  - - ent_coef
    - 0.0
  - - env_wrapper
    - gym_multigrid.envs.mapf_env.FlatMultiGridObsWrapper
  - - gae_lambda
    - 0.95
  - - gamma
    - 0.99
  - - learning_rate
    - 0.00025
  - - n_envs
    - 8
  - - n_epochs
    - 10
  - - n_steps
    - 128
  - - n_timesteps
    - 1000000.0
  - - policy
    - MlpPolicy
  - - policy_kwargs
    - dict( log_std_init=-2, ortho_init=False, activation_fn=nn.ReLU, net_arch=dict(pi=[256,
      256, 256, 256], vf=[256, 256, 256, 256]) )
